apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  CITY: {{ .Values.config.city | quote }}
  SCRAPE_INTERVAL: {{ .Values.config.scrapeInterval | quote }}