apiVersion: v2
name: weather-exporter
description: Exporteur de métriques météo pour Prometheus
type: application
version: 0.1.0        # version du Chart (pas de l'app)
appVersion: "1.0.0"   # version de ton image Docker